security:
    providers:
        user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: user_provider
            guard:
                authenticators:
                    - App\Security\JwtTokenAuthenticator
    encoders:
        App\Entity\User:
            algorithm: auto

    access_control:
        - { path: ^/api/doc$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/(login|register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }